# Generated by Django 5.2.4 on 2025-07-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
