# Generated by Django 5.2.4 on 2025-07-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appointment_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
