# Generated by Django 5.2.4 on 2025-07-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appointment_payment_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_paid',
        ),
    ]
