# Generated by Django 5.2.4 on 2025-07-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_appointment_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
